spring.application.name=brawlSelectorHelp

#Adds keys.properties to application.properties so it can load values
#optional: at the start would make it optional but it is not for this
spring.config.import=classpath:keys.properties

